### PR TITLE
fix: /list_bans formats the fields incorrectly

### PR DESCRIPTION
**Pull request by dtomvan**
Fixes: #48

### CODE REVIEW

**Review by NiteBlock — COMMENTED** [review]
wait why are you changing the config

**Comment by dtomvan** [comment]
It wasn't running without changing my config.toml, and I figured the change should be reflected in Config.example.toml

**Comment by dtomvan** [comment]
```
thread 'main' panicked at 'Config could not be parsed.: Error { inner: ErrorInner { kind: Custom, line: Some(64), col: 0, at: Some(6331), message: "missing field `required_roles`", key: ["pings"] } }', src/consts.rs:87:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by NiteBlock** [comment]
https://i.imgur.com/UvWlwcs.png

**Comment by dtomvan** [comment]
You need to change `required_role` to `required_roles` and make it an array

**Comment by dtomvan** [comment]
Yea I understand

**Comment by NiteBlock** [comment]
You changed to required_role in your config though, it is looking for required_roles

**Comment by NiteBlock** [comment]
ok

**Comment by dtomvan** [comment]
Oh how did that happen

**Comment by NiteBlock** [comment]
lol

**Pull request merged**
