### PR TITLE
Screensharing

### PR DESCRIPTION
**Pull request by dtomvan**
This PR implements the following:
- /screenshare
- /close
- /freeze
- /unfreeze

Closes: #25

Edit: if this is merge I am going to close linked issue, since I'm going to work down the list, then merge this and close it

### CODE REVIEW

**Comment by dtomvan** [comment]
Why did you merge master? I cannot push my stuff right now. I'm resetting it, changing what you told me to do, then we can start testing and merge.

**Comment by NiteBlock** [comment]
I think I broke something

**Comment by NiteBlock** [comment]
Oops

**Comment by dtomvan** [comment]
It's fine. I'm rebasing. Then we can easily fast-forward everything.

**Comment by NiteBlock** [comment]
ok ty

**Comment by dtomvan** [comment]
I think my API key for Hypixel is invalid. That way the test failed.

**Comment by NiteBlock** [comment]
Ah I see

**Comment by NiteBlock** [comment]
probably shouldn't just have the api key there like that

**Pull request merged**
